# ===== Base config for ImageNet-100 (ResNet-50 F1 top-100 subset) =====

# device_type: 0
seed: 67
dataset: imagenet-100
norm_type: imagenet
is_metaformer: true

# ===== Channel mixer =====
channel_mixer: mlp

# ===== Token mixer =====
attn_head_dim: 64
attn_qkv_bias: true
attn_drop: 0.0
attn_proj_drop: 0.0

# ===== Model =====
img_size: 224
patch_size: 16
embed_dim: 192
depth: 12
mlp_ratio: 4.0
norm_layer: layernorm
act_layer: GELU

drop_rate: 0.0
drop_path: 0.1
add_pos_emb: true
use_layer_scale: false
layer_scale_init_value: 1e-5

# ===== Training =====
epochs: 300
train_batch_size: 256
test_batch_size: 256

optimizer: adamw
learning_rate: 6.67e-4
weight_decay: 0.05
decay_type: cosine
warmup_epochs: 10
max_grad_norm: 5.0
eval_interval: 5
label_smoothing: 0.1
augment: strong

# ===== Etc =====
num_classes: 100
num_workers: 8
log_interval: 50
fp16: true
data_path: ./data
save_best: true
no_wandb: false
project: imagenet-100
